export interface Schema{
    "path": string,
    "project": string,
    "name": string,
    "displayBlock": boolean,
    "inlineStyle": boolean,
    "inlineTemplate": boolean,
    "standalone": boolean,
    "viewEncapsulation": string,
    "changeDetection": string,
    "prefix": string,
    "type": string,
    "skipTests": boolean,
    "flat": boolean,
    "skipImport": boolean,
    "selector": string,
    "skipSelector": boolean,
    "module": any,
    "export": boolean,
    "style": string,
}